### ISSUE TITLE
Code coverage badge is not connected to github actions CI

### ISSUE THREAD

**Issue by shimwell** [fusion-energy/openmc-plasma-source#102]

**Comment by RemDelaporteMathurin** [comment]
What should we do about this? It is linked to Codecov which is not running in GA (but triggered by the workflow). I don't think this is an issue

**Comment by shimwell** [comment]
Perhap i have misunderstood but I think we need to run code coverage in the gha ci and upload result. Badge should be pointing to the code coverage currently present on the main branch

**Comment by RemDelaporteMathurin** [comment]
Yes ok, I'm on it
