### ISSUE TITLE
Dead code should be removed

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/openmc-plasma-source#12]
https://github.com/fusion-energy/openmc-plasma-source/blob/fce6e922fb348168d5bc0ab05100e218a1789b88/openmc_plasma_source/tokamak_source.py#L271-L274

This is broken and should be removed

**Comment by mdfaisal98** [comment]
Hi @RemDelaporteMathurin , I would like to work on this issue. Could you assign it to me?
