### ISSUE TITLE
Widen range of matplotlib packages allowed

### ISSUE THREAD

**Issue by shimwell** [fusion-energy/openmc-plasma-source#42]
Is there any chance I can change this line to allow versions above ```3.3.4```

https://github.com/fusion-energy/openmc-plasma-source/blob/e3931d18a9f53dcae23d158bbcd2e291ca3dab34/setup.cfg#L30

I am installing this package in some CI and getting this error

```error: matplotlib 3.3.4 is installed but matplotlib>=3.4.3 is required by {'openmc-plasma-source'}```

Looking at the earlier releases (pre .toml file) it looks like  "matplotlib >= 3.2.2" was accepted

**Comment by RemDelaporteMathurin** [comment]
@LiamPattinson is there a particular reason for this version restriction? if not can we allow matplotlib 3.3.4?

**Comment by LiamPattinson** [comment]
I'm actually not sure why the minimum version was set to 3.4.3. Must have been an oversight when I translated `setup.py` to `setup.cfg`. I'll revert it back to 3.2.2.

**Comment by RemDelaporteMathurin** [comment]
@shimwell can we close this now?
