### ISSUE TITLE
Make requirements.txt

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/openmc-plasma-source#5]
The only dependency here is numpy really, it should be added either as a requirements.txt or in the setup.py

**Comment by mdfaisal98** [comment]
Hi @RemDelaporteMathurin, I'm new to open source contribution and would like to work on this issue.
Any specific version of numpy required?

**Comment by RemDelaporteMathurin** [comment]
Hi @mdfaisal98 

Thanks for willing to contribute.

I don't think any specific version of numpy is required. However, it's good practice to have a specific version in the requirements. Let's have the current latest version of numpy in the requirements for now 😄

**Comment by mdfaisal98** [comment]
Thanks for the info @RemDelaporteMathurin !

**Comment by mdfaisal98** [comment]
Hi @RemDelaporteMathurin , I created a new branch off main named requirements and made the changes. But I'm not able to push my changes. Keep getting the following error -
`git push --set-upstream origin requirements
info: please complete authentication in your browser...
remote: Permission to fusion-energy/openmc-plasma-source.git denied to mdfaisal98.
fatal: unable to access 'https://github.com/fusion-energy/openmc-plasma-source.git/': The requested URL returned error: 403
`

**Comment by RemDelaporteMathurin** [comment]
@mdfaisal98 you can't push to this repository because you don't have write access.

First you need to "fork" this repository, clone your fork ("it will be mdfaisal98/openmc-plasma-source ), make the changes, push on your fork, then create a PR (Pull Request)

**Comment by mdfaisal98** [comment]
@RemDelaporteMathurin I have raised a PR. Please review it.
