### ISSUE TITLE
"shafranov factor" units should be in cm 

### ISSUE THREAD

**Issue by Oliverator** [fusion-energy/openmc-plasma-source#86]
Hi John,

This is Mario Oliver (KF). I don't have much experience in GitHub so excuse me if this is not the right way to raise a comment on someone else's code.

I detected that in "src/openmc_plasma_source/tokamak_source.py", lines 42-44, shafranov_factor (float) should be defined in cm, not m.

Otherwise, formula in line 330 does not match.

Hope this is useful.
Best regards,

Mario

**Comment by shimwell** [comment]
Thanks Mario

I've put in a [pull request](https://github.com/fusion-energy/openmc-plasma-source/pull/87) to correct the units. Thanks for pointing out the error so clearly.

**Comment by RemDelaporteMathurin** [comment]
Hi Mario! Good to see you hear! 

Thanks for reporting this!

Cheers
Rémi
